[package]
name = "diff_confused_rest_interface"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
prost = "0.11"

[build-dependencies]
prost-build = "0.11"
