name: run clippy

permissions:
  pull-requests: write

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v2
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D clippy::all
