name: check formatting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v2
      - run: cargo fmt --all --check
