name: run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v2
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace
